model:
  model_name_or_path: "Qwen/Qwen2.5-0.5B-Instruct"

train:
  # GRPO-specific
  num_problems_per_batch: 4   # Number of problems per batch
  group_size: 4               # Number of attempts per problem
  beta: 0.000004

  # Optimisation
  gradient_accumulation_steps: 1   # num_problems_per_batch * group_size / gpus
  max_steps: 1000

  gradient_checkpointing: true

  ref_model_inference_batch_size: 4

logging:
  wandb: true
  wandb_project: "train-grpo"
  wandb_run_name: "Qwen-0.5b"
  wandb_entity: "rd211"
  run_group: "0.5b"
  wandb_tags: ["0.5b"]

checkpoint:
  save_steps: 100000
  save_total_limit: 3
  save_dir: "/iopsstor/scratch/cscs/ddinucu/GRPO/checkpoints/qwen-0.5b"

seed: 42
server_port: 8005
